[package]
name = "protobuf_build"
version = "0.1.1"
authors = ["Paul Lietar <paul@lietar.net>"]
build = "build.rs"

[dependencies]
protobuf = "~1.4.3"
libc = "~0.2.4"

[build-dependencies]
gcc = "~0.3.21"
pkg-config = "~0.3.6"
